version: '3.8'

services:
  loan-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loan-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:loanapi
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
    depends_on:
      - h2-database

  h2-database:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "8082:8082"  # H2 Console
      - "9092:9092"  # H2 TCP Server
    environment:
      - H2_OPTIONS=-web -webAllowOthers -tcp -tcpAllowOthers
    volumes:
      - h2-data:/opt/h2-data

volumes:
  h2-data: